<a href="https://colab.research.google.com/github/jarkuszewski/NeuralNetworks/blob/main/DigitRecognizationByPerceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import keras.preprocessing.image as kpi
from matplotlib import pyplot as plt

def perceptronlearning(smallDimm, bigDimm, E, T):
  learningEta = 0.1
  lifeTime = 0
  bestLifeTime = lifeTime
  theta = np.random.default_rng().uniform(-1,1, 1)[0]
  weights = np.random.default_rng().uniform(-1,1, smallDimm)
  bestWeights = weights
  iterations = 100
  good = np.full((bigDimm[0],bigDimm[1]),False)

  counter = 0
  bestCounter = 0

  for index in range(iterations):
    i = np.random.randint(bigDimm[0])  
    j = np.random.randint(bigDimm[1])  

    O = 1 if np.dot(weights.flatten(), E[i][j].flatten()) - theta >= 0 else -1
    print("O = {} dla {}".format(O, E[i][j]))
    ERR = T[i][j] - O
    print("ERR = {} dla {}".format(ERR, E[i][j]))
    print
      
    if ERR != 0: 
        lifeTime = 0
        counter = 0
        good = np.full((bigDimm[0], bigDimm[1]), False)
        weights += learningEta * ERR * T[i][j]
        theta -= learningEta * ERR     
    else:
        lifeTime += 1
        if not good[i][j]:
          good[i][j] = True
          counter += 1
        if bestLifeTime < lifeTime and bestCounter < counter:
          bestLifeTime = lifeTime
          bestCounter = counter
          bestWeights = weights
    
    weights = bestWeights

if __name__ == "__main__":
  
  array = np.array([])
  mainImg = kpi.load_img("cyfryN.png")

  allImages = kpi.img_to_array(mainImg)
  allImages /= 255

  bigDimm = (10,8)
  #7x5 
  smallDimm = (allImages.shape[0] // 10, allImages.shape[1] // 8)
  


  for i in range(bigDimm[0]):
    row = np.array([])
    for j in range(bigDimm[1]):
      singleImage = allImages[
        i * smallDimm[0]: (i+1) * smallDimm[0],
        j * smallDimm[1]: (j+1) * smallDimm[1]
      ][:,:,0]
      row = np.append(row, singleImage)
    array = np.append(array, row)

  array = array.reshape(
    bigDimm[0],
    bigDimm[1],
    smallDimm[0],
    smallDimm[1]
    )
  

  for i in range(10):
    A = array[i]
    B = np.delete(array, i , 0)
    E = np.zeros((
        bigDimm[0],
        bigDimm[1],
        smallDimm[0],
        smallDimm[1]
        ))
    E = B
    E = np.insert(E, i ,A, axis = 0)

    T = np.zeros((bigDimm[0], bigDimm[1]))

    T[:,:] = -1
    T = np.insert(T , i , 1, axis = 0)

    print(perceptronlearning(smallDimm,bigDimm,E,T))
    

Strumieniowane dane wyjściowe obcięte do 5000 ostatnich wierszy.
 [0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
ERR = 0.0 dla [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
O = 1 dla [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
ERR = 0.0 dla [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
O = 1 dla [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 1.]]
ERR = -2.0 dla [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 1.]]
O = 1 dla [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1.]]
ERR = -2.0 dla [[0. 0. 0. 0